name: anu_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  #Packages
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_spinkit: ^5.1.0
  rive: ^0.12.3
  url_launcher: ^6.2.4
  syncfusion_flutter_pdfviewer: ^24.2.3
  get_storage: ^2.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/calculator.png
    - assets/images/anu.jpg
    - assets/images/bajes.jpeg
    - assets/RiveAssets/
    - assets/images/record.jpg
    - assets/PDF/feesPdf.pdf
    - assets/PDF/Calender.pdf
    - assets/images/gpa.png
    - assets/images/record.jpeg
    - assets/images/faq.png
    - assets/images/facebook.png
    - assets/images/library.png
    - assets/images/zahi.jpg
    - assets/images/mutasem.jpg
    - assets/images/gazi.jpg
    - assets/images/doctor.jpg
    - assets/images/bajes2.jpg
    - assets/images/elearn.png
    - assets/images/moodle.jpg
    - assets/images/teams.jpg
    - assets/images/infoto.jpg
    - assets/images/howto.jpg
    - assets/images/whatsapp.jpg
    - assets/images/itDoctors.jpg
    - assets/images/AnuDoctors.jpg
    - assets/images/mohamedBaniYounes.jpg
    - assets/images/yaserAlsharee.jpg
    - assets/images/amerAboJassar.jpg
    - assets/images/Literature/AliKharabsheh.jpg
    - assets/images/Literature/mansouralyasreh.png
    - assets/images/Literature/abedalrahemmarashdeh.jpeg
    - assets/images/Literature/muhanedaljabali.jpg
    - assets/images/Literature/zuheraloroud.jpg
    - assets/images/Literature/sameralzubi.jpg
    - assets/images/Literature/amenlmaisah.jpg
    - assets/images/Literature/mahmoudalsobh.jpg
    - assets/images/Literature/khakedaljabli.jpg
    - assets/images/Literature/mohamedalamirah.jpg
    - assets/images/Literature/khaledshraidah.jpg
    - assets/images/Literature/ahmedalqudah.jpg
    - assets/images/Literature/alialobdi.jpg
    - assets/images/Law/lawcolage.jpg
    - assets/images/Law/mohamedfreihat.jpg
    - assets/images/Law/ahmedbtoush.jpg
    - assets/images/Law/mohamedbanymekdad.jpg
    - assets/images/Law/talalalesa.jpg
    - assets/images/Law/essalafismadi.jpg
    - assets/images/Law/zyadalwashat.jpg
    - assets/images/Law/muntaseralqudah.jpg
    - assets/images/Law/drhashembls.jpg
    - assets/images/Law/ahmedalamawi.jpg
    - assets/images/Law/galebalsmailah.jpg
    - assets/images/Law/salemalsawli.jpg
    - assets/images/Law/dr.mamoonsmadi.jpg
    - assets/images/Law/dr-tafweg.jpg
    - assets/images/works/colageofwork.jpg
    - assets/images/works/nedalalqudah.jpg
    - assets/images/works/heshamshantawi.jpg
    - assets/images/works/belalmatani.jpg
    - assets/images/works/muhanedalebini.jpg
    - assets/images/works/laithaleryan.jpg
    - assets/images/works/dralialzubi.jpg
    - assets/images/works/mohaidenabohol.jpg
    - assets/images/works/khaledalomari.jpg
    - assets/images/works/jorjshwakfah.jpg
    - assets/images/works/mohamedjradat.jpg
    - assets/images/works/mohamed_alqudah.jpg
    - assets/images/works/mohamed_alzhoul.jpg
    - assets/images/works/mohamedalmomani.jpg
    - assets/images/works/kasemabued.jpg
    - assets/images/works/khaleddebat.jpg
    - assets/images/works/qadro_ashukri.jpg
    - assets/images/works/hasenalwhshat.jpg
    - assets/images/Engineering/CollegeofEngineering.jpg
    - assets/images/itCollage.jpg
    - assets/images/Engineering/ahmedfrehat2.jpg
    - assets/images/Engineering/dr.ahmedsalameh.jpg
    - assets/images/Engineering/dr.zyad-shbol.jpg
    - assets/images/Science/science.jpg
    - assets/images/Science/anasmasarwah.jpg
    - assets/images/Science/abdalazez.png
    - assets/images/Science/dr_hamazh-kasasbeh.jpg
    - assets/images/Science/ali_alotoum.png
    - assets/images/Science/mohamed_alhmori.jpeg
    - assets/images/Educational Sciences/EducationalSciences.jpg
    - assets/images/Agriculture/Agriculture.jpg
    - assets/images/Educational Sciences/khaledalmomaniedu.jpg
    - assets/images/Educational Sciences/amjaddradkh1.png
    - assets/images/Educational Sciences/dr.mohamedalsadi.jpg
    - assets/images/Educational Sciences/mosaabuzaiton.png
    - assets/images/Educational Sciences/rabialzgoul.jpg
    - assets/images/Educational Sciences/saleh_dradkah.png
    - assets/images/Educational Sciences/fesalnwasrah.png
    - assets/images/Educational Sciences/dr.brhan.jpg
    - assets/images/Educational Sciences/khaledebedat.png
    - assets/images/Educational Sciences/mohamedalomarita.jpg
    - assets/images/Educational Sciences/nayafalwahshah.png
    - assets/images/Agriculture/dribrahem.jpg
    - assets/images/Agriculture/drorwah.jpg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Circular
      fonts:
       - asset: assets/fonts/circular-std-medium-500.ttf

    - family: DGEnab
      fonts:
       - asset: assets/fonts/FFShamelFamily-SansOneBold.ttf

    - family: DGNemr
      fonts:
      - asset: assets/fonts/FFShamelFamily-SansOneBold.ttf

  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
assets/images/Engineering/CollegeofEngineering:
  jpg:
